# Generated by Django 5.2.4 on 2025-08-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='cryptocurrency',
            field=models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('TRX', 'Tron'), ('LTC', 'Litecoin')], default=123, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='user_email',
            field=models.EmailField(default=123, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saletransaction',
            name='wallet_address',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
