# Generated by Django 5.2.4 on 2025-08-09 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_saletransaction_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('robux_amount', models.IntegerField()),
                ('fiat_currency', models.CharField(default='USD', max_length=10)),
                ('fiat_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('cryptocurrency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('TRX', 'Tron'), ('LTC', 'Litecoin')], max_length=10)),
                ('crypto_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('encrypted_cookie', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('paid', 'Выплачено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
