# Generated by Django 5.2.4 on 2025-08-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='cryptocurrency',
            field=models.CharField(choices=[('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('LTC', 'Litecoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='cryptocurrency',
            field=models.CharField(choices=[('ETH', 'Ethereum'), ('USDT', 'Tether (USDT)'), ('LTC', 'Litecoin')], max_length=10),
        ),
    ]
