# Generated by Django 5.2.4 on 2025-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_saletransaction_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saletransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('paid', 'Выплачено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='robloxaccount',
            name='roblox_cookie_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('paid', 'Выплачено')], default='pending', max_length=10),
        ),
    ]
