# Generated by Django 5.2.4 on 2025-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_saletransaction_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='encrypted_cookie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
