# Generated by Django 5.2.4 on 2025-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_withdrawalrequest_encrypted_cookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='cryptocurrency',
            field=models.CharField(choices=[('USDT', 'trc20'), ('USDT', 'bep20'), ('LTC', 'Litecoin')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='cryptocurrency',
            field=models.CharField(choices=[('USDT', 'trc20'), ('USDT', 'bep20'), ('LTC', 'Litecoin')], max_length=10),
        ),
    ]
