# Generated by Django 5.2.4 on 2025-08-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_saletransaction_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawalrequest',
            old_name='encrypted_cookie',
            new_name='decrypted_cookie',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='fiat_amount',
        ),
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='fiat_currency',
        ),
        migrations.AlterField(
            model_name='saletransaction',
            name='cryptocurrency',
            field=models.CharField(choices=[('trc20', 'USDT'), ('bep20', 'USDT'), ('ltc', 'LTC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='cryptocurrency',
            field=models.CharField(choices=[('trc20', 'USDT'), ('bep20', 'USDT'), ('ltc', 'LTC')], max_length=10),
        ),
    ]
