# Generated by Django 5.2.4 on 2025-08-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_encrypted_cookie_withdrawalrequest_decrypted_cookie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saletransaction',
            name='cryptocurrency',
            field=models.CharField(choices=[('trc20', 'USDTtrc20'), ('bep20', 'USDTbep20'), ('ltc', 'LTC')], max_length=10),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='cryptocurrency',
            field=models.CharField(choices=[('trc20', 'USDTtrc20'), ('bep20', 'USDTbep20'), ('ltc', 'LTC')], max_length=10),
        ),
    ]
