# Generated by Django 5.2.4 on 2025-08-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_saletransaction_cryptocurrency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robloxaccount',
            name='rate',
            field=models.FloatField(choices=[(0.001, '1$ за 1000 Robux'), (0.002, '2$ за 1000 Robux'), (0.003, '3$ за 1000 Robux'), (0.004, '4$ за 1000 Robux'), (0.005, '5$ за 1000 Robux')], default=0.003, verbose_name='Курс продажи'),
        ),
    ]
