# Generated by Django 5.2.4 on 2025-08-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_robloxaccount_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='crypto_amount',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='dollar_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
            preserve_default=False,
        ),
    ]
