# Generated by Django 5.2.4 on 2025-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_withdrawalrequest_crypto_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robloxaccount',
            name='rate',
            field=models.FloatField(choices=[(0.003, '3.0$ за 1000 Robux'), (0.0031, '3.1$ за 1000 Robux'), (0.0032, '3.2$ за 1000 Robux'), (0.0033, '3.3$ за 1000 Robux'), (0.0034, '3.4$ за 1000 Robux'), (0.0035, '3.5$ за 1000 Robux'), (0.0036, '3.6$ за 1000 Robux'), (0.0037, '3.7$ за 1000 Robux'), (0.0038, '3.8$ за 1000 Robux'), (0.0039, '3.9$ за 1000 Robux'), (0.004, '4.0$ за 1000 Robux'), (0.0041, '4.1$ за 1000 Robux'), (0.0042, '4.2$ за 1000 Robux'), (0.0043, '4.3$ за 1000 Robux'), (0.0044, '4.4$ за 1000 Robux'), (0.0045, '4.5$ за 1000 Robux'), (0.0046, '4.6$ за 1000 Robux'), (0.0047, '4.7$ за 1000 Robux'), (0.0048, '4.8$ за 1000 Robux'), (0.0049, '4.9$ за 1000 Robux'), (0.005, '5.0$ за 1000 Robux')], default=0.003, verbose_name='Курс продажи'),
        ),
    ]
